data_dir: ${oc.env:PROJECT_ROOT}/data
output_dir: ${oc.env:PROJECT_ROOT}/outputs
checkpoint_dir: ${paths.output_dir}/checkpoints
model_dir: ${oc.env:PROJECT_ROOT}/model-data
results_dir: ${paths.model_dir}/results 